#!/usr/bin/env bash
#Write a Bash script that:

#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# creating the file myscript.pid
echo $$ > /var/run/myscript.pid
#trap SIGTERM and SIGQUIT signals to delete the PID file and terminate the script
trap "rm -f /var/run/myscript.pid; echo 'Exiting gracefully'; exit 0" SIGTERM SIGQUIT

# trap SIGINT signal to display a message
trap "echo 'Y U no love me?!'" SIGINT

# display a message indefinitely
echo "To infinity and beyond!"

# trap SIGTERM signal to display a message
trap "echo 'I hate the kill command'" SIGTERM

# loop indefinitely
while true; do
    sleep 1
done

