#!/usr/bin/env bash
#Bash script that displays "Best School" 10 times.
#Requirement:
#You must use the for loop (while and until are forbidden)

i=0
for ((i = 1; i<= 10; i++));
do
	echo "Best School"
done
